# Add configuration values here, as shown below.
#
# pusher_app_id: "2954"
# pusher_key: 7381a978f7dd7f9a1117
# pusher_secret: abdc3b896a0ffb85d373
# stripe_api_key: sk_test_2J0l093xOyW72XUYJHE4Dv2r
# stripe_publishable_key: pk_test_ro9jV5SNwGb1yYlQfzG17LHK
#
# production:
#   stripe_api_key: sk_live_EeHnL644i6zo4Iyq4v1KdV9H
#   stripe_publishable_key: pk_live_9lcthxpSIHbGwmdO941O1XVU

GMAIL_USERNAME: 'notmisokuan@gmail.com'
GMAIL_PASS: 'n0tm1s0ku@n'

MERCHANT_ID: bgjs95r8kkf6gr5t
PUBLIC_KEY: zb3cpzbcnmzj6hnv
PRIVATE_KEY: 1b3cc0070e41db5c8d72ebbf671611ec

AWS_ACCESS_KEY: 'AKIAJLLFGNBVSEBSHT3A'
AWS_SECRET_ACCESS_KEY: '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'
AWS_BUCKET: 'avatarimage'